#Lab01 - Getting Started 

Name: Samuel Baldwin
Class: CSCI 349 - Intro to Data Mining
Section: 01 - 11am
Semester: Spring 2024
Instructors: Brian King

**2.** [M]  Did you read the syllabus? All of it? Do you understand and agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating. 

Yes I have read through the syllabus, in its entirety. 
I understand and agree to abide by the cheating rules laid out within the syllabus. 
I will not cheat on material in this class, and will follow the Bucknell University Honor Code throughout the duration of this course. 

**3.** [M] What are you hoping to get out of this course

My goal for this class is to get a solid understanding of the basics of data mining, given that it is a fiald in which I have no prior experience. I want to be able to understand the basic concepts so that I can form my own opinions on the material.


**4.** [P] Print the Python Version (available in sys package)

In [165]:
import sys 
print(sys.version)

3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]


**5.** [P] Create a Python list of 1000 random integers in the rage 1 to 100 using the random package. Name the list x_list

In [166]:
import random
x_list = [] #Create an empty list 
for i in range(10000):
    x_list.append(random.randint(1,99))


**6.** [P] What is the minimum value of x_list? What is the max value? What is the mode? 

In [167]:
from statistics import mode 
print(f'The min of x_list is:  {min(x_list)}.')
print(f'The max of x_list is:  {max(x_list)}.')
print(f'The mode of x_list is:  {mode(x_list)}.')

The min of x_list is:  1.
The max of x_list is:  99.
The mode of x_list is:  53.


**7.** [P] Write a function to take a list of numbers as a parameter and return the average of the list. Then use your function to report the average value of x_list, printed as a float with 2 places of precision.

In [168]:
def average_list(list):
    sum = 0
    for element in list: 
        sum += element
    average = (1.0) * sum / len(list)
    print(f'The average of x_list is:  {round(average, 2)}')
average_list(x_list)

The average of x_list is:  49.72


**8.** [P] Create a list called x_hist that represents a *histogram*, i.e a distribution of the numerical data, of *x_list*. Each entry in *x_hist* should contain the frequency of data over a bin width of 10. So, for example, *x_hist[0]* represents the frequeny of numbers between 1-10, *x_hist*[1] is the frequency of numbers between 11-10, and so on. Be sure to print *x_hist* at the end. (Do NOT use numpy!)

In [169]:
x_hist = [0] * 10
for element in x_list: 
    x_hist[(element//10)] += 1 
print(x_hist)


[916, 1002, 1018, 1065, 994, 1020, 1034, 946, 996, 1009]


**9** [M] What is numpy? What are its strengths? Does it have any weaknesses?

Numpy is a packaged for python designed to add support for multidimensional arrays and matrices, as well as functions that can be applied to arrays in order to draw conclusions. \
Its strengths are in these arrays which allow for easy creation and adjustment of multidimensional matrices, and the relatively lightweight nature of those matrices allowing for fast efficient computation.\
Its weaknesses generally lie in the fact that it doesn't have many effective mechanisms for displaying the arrays, so it can be difficult to visualize and present data that has been made into arrays. 


**10.** [P] Import the numpy package as np and print the numpy version

In [170]:
import numpy as np
print(np.__version__)

1.23.4


**11.** [M] What is the primary object type in numpy? Can it store data of different types? Discuss.

The primary object type is the np.array type. \
The np.array can store differenty types of data, such as ints or floats

**12.** [M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how they type system is different than the built-in types int and float in Python. 


Numpy has integer, floating point, boolean, object, and string types. \
Numpy also offers the capability of denoting the spacific depth of integers and floats, from 8 to 64 bits for both. Numpy also offers unsigned integers. 

**13.** [P] Research how to use numpy to compute the same result as problem 8 above. (HINT: np.histogram)

In [171]:
numpy_array = np.array(x_list)
histogram = np.histogram(numpy_array, bins = np.arange(0, 110, 10))
print(histogram)

(array([ 916, 1002, 1018, 1065,  994, 1020, 1034,  946,  996, 1009]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


**14.** [P] Create a numpy array from x_list. Reassign it as x_list. Show the contents of the first 20 entries. 

In [172]:
x_list = np.array(x_list)
print(x_list[:20])

[29 59 42 13 75 24 42 88 93 96 22 43 15 17 51 72 88 77 75 46]


**15.** [P] Redo the previous exercise but set the data type of each value to 'float32'

In [173]:
x_list_float32 = x_list.astype(np.float32)
print(x_list_float32)

[29. 59. 42. ... 30. 89. 33.]


**16.** [P] Create a length 10 integer array filled with zeros 

In [174]:
zeros_array = np.zeros(10, dtype=int)
print(zeros_array)

[0 0 0 0 0 0 0 0 0 0]


**17** [P] Create a float array of 3 rows and 4 columns, all initialized to one. 


In [175]:
three_by_four = np.ones((3,4))
print(three_by_four)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**18.** [P] Create an array of 30 values, evenly spaced between 1 and 3 (HINT - look at np.linespace)

In [176]:
evenly_spaced = np.linspace(1,3,20)
print(evenly_spaced)

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


**19.** [P] Set the numpy random seed to the value 12345, then create a 10x5 array of random itegers on the inverval 10,50 assigned to x_mat.

In [177]:
np.random.seed(12345)
x_mat = np.random.randint(10, 51, size=(10,5))
print(x_mat)

[[44 47 39 11 46]
 [47 44 39 11 24]
 [37 26 19 21 23]
 [20 27 28 48 17]
 [49 33 39 41 43]
 [37 33 46 10 13]
 [15 25 21 24 27]
 [15 44 18 15 44]
 [15 29 22 24 26]
 [37 48 34 42 15]]


**20.** [P] Use slicing to select and show the first and last row of x_mat

In [178]:
print(x_mat[[0,-1]])

[[44 47 39 11 46]
 [37 48 34 42 15]]


**21.** [P] Now, show the first third and fifth column of x_mat

In [179]:
print(x_mat[:, [0,2,4]])

[[44 39 46]
 [47 39 24]
 [37 19 23]
 [20 28 17]
 [49 39 43]
 [37 46 13]
 [15 21 27]
 [15 18 44]
 [15 22 26]
 [37 34 15]]


**22.** [P] Show the sum of each row. Your output should appear like this:

In [180]:
print(np.sum(x_mat, axis=1))

[187 165 126 140 205 139 112 136 116 176]
