# Lab 03 - pandas I

Name: Samuel Baldwin  
Class: CSCI 349 - Intro to Data Mining  
Section: 01 
Semester: Spring 2024
Instructors: Brian King, Joshua Stough


**Submission:** 
* `lab03.ipynb`, pushed to your Git repo on master.   
* `lab03.pdf` generated and turned in on Gradescope

**Points**: 10

**Due**: NOTE: This is part 1. Part 2 (lab04) will be released early next week. Both are due on Friday, Feb 2, 11:59 PM.

# Objectives

-   pandas.

# Introduction

Numpy is a core, foundational Python library for use in many domains. And, it works well. It is efficient, designed for high performance computing, having been mostly written in the C language. And, it works quite well when your data is clean, structured, and uniform types. However, most real-world data is large, messy, heterogeneous, and often incomplete, with missing values. `pandas` has been developed for the data science community to aid in dealing with real world data. It will help you handle the vast majority of the data prepping, cleaning, filtering, munging, etc. that you will be doing. It also does a fantastic job providing you with a pretty impressive data selection API. Therefore, you MUST become confident with pandas. This is the first part of a 2-part lab designed to help you become familiar with pandas.

## Useful References

- [10 minute `pandas` intro](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [`pandas` docs](http://pandas.pydata.org/pandas-docs/stable/index.html)

A large portion of this lab is taken from snippets scattered throughout the enormous documentation and tutorials from the pandas website. In particular, the [short intro video](http://pandas.pydata.org/pandas-docs/stable/10min.html) linked above will get you going pretty quickly with the most common tasks you'll be doing. It doesn't do a great job really explaining the "how" and "why" that's happening behind the scenes, but you'll learn those through experience. I recommend that you work through the 10 minute introduction above first. Doing so will make the work in this lab so much easier to follow through. Then come back here to work through the exercises. More advanced pandas exercises are coming in part 2!


# Imports
We'll set up the imports for you...


In [132]:
import sys
from builtins import print

import numpy as np
import pandas as pd

# Exercises

Add Code or Markdown cells below each exercise as required.

**1** [P] Report the Python, Numpy and Pandas version numbers.

In [133]:
print(f'Python: {sys.version}')
print(f'Numpy: {np.__version__}')
print(f'Pandas: {pd.__version__}')



Python: 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
Numpy: 1.26.3
Pandas: 2.1.4


**2** [P] Now, show the result of pd.show_versions(). Write a comment in the cell about what this shows.

In [134]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 21.6.0
Version             : Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64
machine             : x86_64
processor           : i386
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : 

The start of Chapter 5 in McKinney's book, ["Python for Data Analysis"](https://learning.oreilly.com/library/view/python-for-data/9781098104023/ch05.html), has an excellent explanation about the relationship between numpy and pandas. Also, don't forget the pandas user guide!

Let's go through some interview questions about pandas. This document will serve as a good reference for yourself as you move forward, so resist laziness! Write good answers that you could use to help you review and prepare for a data science, data mining, or machine learning interview!

**3** [M] Explain the relationship between numpy and pandas. How are they tied together? How are they different? What core functionality does pandas add to numpy?

ANSWER: Numpy is a library that focuses around creating multidimensional arrays to store data. Pandas is more visually focused library that is used to display data in digestible and understandable formats for the human eye to interpret. Pandas is partially built off of numpy arrays and expands them into two different structures, those being Series and DataFrames. A main difference between the two is that while pandas can work with different data types within a structure, numpy cannot.  


**4** [M] Compare and contrast Series and DataFrame.

ANSWER:
A Series is a one-dimensional labeled data structure that can hold any data type. Every index in a Series has an associated value similar to python dictionaries. 
A DataFrame is a two-dimensional labeled data structure, similar to a table. Columns in a DataFrame can hold any data type, and is often associated as a collection of Series, where each column in a DataFrame is a series. 


**5** [M] What are the data types that can be used to create a Series object in pandas?

ANSWER: Series objects are not restricted by data type when created, they can hold numeric, string, boolean, categorical and object types. 



**6** [M] What are the data structures that can be used to create a DataFrame object in pandas?

ANSWER: Numpy arrays, all data types, and python dictionaries can all be used to create DataFrame objects.  



**7** [M] When creating a Series object, what role does the index parameter play? Does the index always need to be specified? If not, what happens?

ANSWER:The index parameter is utilized to access variables within the Series object. Indexes do not need to be specified and if left unspecified, indexes will be [0, len(Series)]




**8** [P] Create a numpy array of 10 random 8-bit integers in the range [10,20) using numpy's randint function. Print the type of x, and show x. You may end up with something like:

```python
type(arr): <class 'numpy.ndarray'>
[0]: 10
[1]: 19
[2]: 18
[3]: 11
[4]: 17
[5]: 12
[6]: 18
[7]: 14
[8]: 13
[9]: 15
```

In [135]:
x = np.random.randint(10, 20, size=10, dtype=np.int8)
print(type(x))
x

<class 'numpy.ndarray'>


array([10, 10, 11, 11, 15, 13, 19, 17, 15, 16], dtype=int8)

Then in a subsequent cell, wrap x in a pandas `Series` object called x2, with an index of 0, 10, 20, 30, …, 90. Show the type and the contents of x2. You should have something like the following, clearly showing your index label on each number:

```python
type(x2): <class 'pandas.core.series.Series'>
0     10
10    19
20    18
30    11
40    17
50    12
60    18
70    14
80    13
90    15
dtype: int64
```

In [136]:
x2 = pd.Series(x, index = range(0,100,10), dtype = np.int64)
x2

0     10
10    10
20    11
30    11
40    15
50    13
60    19
70    17
80    15
90    16
dtype: int64

**9** [P] Create a `DataFrame` object called df_x that has x2 as the first variable with the name of "x2", and an additional variable named "x3" that is 10 random floating point numbers in the range [100,200). Show the types of your dataframe using `print(df_x.dtypes)`, and show the contents of your dataframe. Your index should remain as 0, 10, 20, … , 90. It should look something like this (though your numbers may differ):```

```python
df_x.dtypes:
x2      int64
x3    float64
dtype: object
df_x:
    x2          x3
0   16  172.896501
10  13  185.673105
20  17  179.285031
30  12  113.509989
40  12  166.289903
50  11  176.019581
60  11  184.072302
70  18  182.045494
80  11  160.123833
90  19  154.065640
```


In [76]:
df_x = pd.DataFrame(data = {'x2': x2, 'x3': np.random.uniform(100,200,size= 10)})
print(df_x.dtypes)
df_x

x2      int64
x3    float64
dtype: object


x2          x3
0   16  199.441873
10  13  100.681573
20  15  106.638210
30  18  169.794511
40  11  170.247031
50  17  196.250177
60  10  105.072075
70  13  189.974979
80  11  155.573557
90  19  181.277864

**10** [M] Consider the `copy()` method of a DataFrame object. What is this method for? Explain the difference between a shallow copy and a deep copy of a DataFrame? Why would I use a shallow copy?

ANSWER: The copy() method of a DataFrame object will create a deep copy of the provided DataFrame. This deep copy will be completely independent of the original DataFrame object, and can be modified without changing the original. In contrast, a shallow copy, when changed will adjust the original object. Shallow copies are generally used in cases where the state of the original isn't something you care about and want to quickly and effectively copy something without taking too much space. 




Next, we're going to work with a very simple set of data of quiz scores similar to the previous lab, just to get you started. Enter the following Python lists in a cell in your notebook. They will represent some fictitious daily quiz scores for a couple of weeks of some course you are taking:

```python
days = ["Mon","Tue","Wed","Thu","Fri"] 
scores_1 = [9.5, 8.75, 8, 10, 7.75] 
scores_2 = [9, 8, 10, 8.75, 7.25]
```

In [77]:
days = ["Mon","Tue","Wed","Thu","Fri"] 
scores_1 = [9.5, 8.75, 8, 10, 7.75] 
scores_2 = [9, 8, 10, 8.75, 7.25]

**11** [P] Convert `scores_1` and `scores_2` into two `Series` objects. Use days as your index. You should name each Series object using the name parameter as "week_1", and "week_2". Do not show the result, only store the variables.


In [78]:
week_1 = pd.Series(scores_1, index = days, name = "week_1")
week_2 = pd.Series(scores_2, index = days, name = "week_2")


**12** [P] Create a pandas `DataFrame` called `scores` that represents the above data. Show your data frame. Your results should be arranged as shown below:

```python
scores:
        Mon   Tue   Wed    Thu   Fri
week_1  9.5  8.75   8.0  10.00  7.75
week_2  9.0  8.00  10.0   8.75  7.25
```

In [79]:
scores = pd.DataFrame([week_1, week_2])
scores

Mon   Tue   Wed    Thu   Fri
week_1  9.5  8.75   8.0  10.00  7.75
week_2  9.0  8.00  10.0   8.75  7.25

**13** [P] Use the `pd.concat` function to add the following data to the end of scores: `[8.5,8,9.75,9,8.25]`. The row label on the new week is "week_3". Show your updated data frame. It should look like the following:

```python
scores:
        Mon   Tue    Wed    Thu   Fri
week_1  9.5  8.75   8.00  10.00  7.75
week_2  9.0  8.00  10.00   8.75  7.25
week_3  8.5  8.00   9.75   9.00  8.25
```

In [80]:
week_3 = pd.Series([8.5,8,9.75,9,8.25], index = days, name = "week_3")
scores = pd.concat([scores, pd.DataFrame(week_3).transpose()], axis=0)
scores

Mon   Tue    Wed    Thu   Fri
week_1  9.5  8.75   8.00  10.00  7.75
week_2  9.0  8.00  10.00   8.75  7.25
week_3  8.5  8.00   9.75   9.00  8.25

---
## Selecting Data

You are about to practice a lot of data selection and manipulation techniques. Developing the ability to quickly select data you are looking for is an important skill.

**14** [M] `numpy` and `pandas` have an ENORMOUS number of ways for selecting data. At first, the flexibility will confuse and drive you nuts. In time, it becomes amazing and intuitive (with less nuts.) From their 10 minute tutorial: 

> Note: While standard Python / Numpy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, `.at`, `.iat`, `.loc`, and `.iloc`


Write yourself a quick one sentence reference for each access method listed above, with one example for each using the `scores` DataFrame.

ANSWER:




In [81]:
# Your examples using scores go here.
print(scores.at["week_1", "Mon"])
print(scores.iat[0, 0])
print(scores.loc["week_1"])
print(scores.iloc[0])

9.5
9.5
Mon     9.50
Tue     8.75
Wed     8.00
Thu    10.00
Fri     7.75
Name: week_1, dtype: float64
Mon     9.50
Tue     8.75
Wed     8.00
Thu    10.00
Fri     7.75
Name: week_1, dtype: float64


You are going to see many ways to select data in a DataFrame. It will be confusing at first. For example, in addition to the above access methods, you can also use the `[ ]` operator directly to access your data. Want to see just how flexible data selection is in Pandas? Suppose you simply wanted to grab the data for Mondays over all three weeks. How would you do that? I've seen all these as possible answers. Try out the following, placing each in separate cells by themselves: 

```python
scores.iloc[0]
scores.iloc[0:1]
scores.iloc[:,0:1]
scores[0:1]
scores.Mon
scores["Mon"]
scores.loc[:,"Mon"] 
scores.loc[:,["Mon"]] 
```

and understand how they are the same (or different!) Be careful, because many of these may appear to return the same result, but the actual pandas type represented is entirely different. (For example, `scores.iloc[0]` returns a Series. `scores.iloc[0:1]` returns a DataFrame.)

In [82]:
scores.iloc[0]

Mon     9.50
Tue     8.75
Wed     8.00
Thu    10.00
Fri     7.75
Name: week_1, dtype: float64

In [83]:
scores.iloc[0:1]

Mon   Tue  Wed   Thu   Fri
week_1  9.5  8.75  8.0  10.0  7.75

In [84]:
scores.iloc[:,0:1]

Mon
week_1  9.5
week_2  9.0
week_3  8.5

In [85]:
scores[0:1]

Mon   Tue  Wed   Thu   Fri
week_1  9.5  8.75  8.0  10.0  7.75

In [86]:
scores.Mon

week_1    9.5
week_2    9.0
week_3    8.5
Name: Mon, dtype: float64

In [87]:
scores["Mon"]

week_1    9.5
week_2    9.0
week_3    8.5
Name: Mon, dtype: float64

In [88]:
scores.loc[:,"Mon"] 

week_1    9.5
week_2    9.0
week_3    8.5
Name: Mon, dtype: float64

In [89]:
scores.loc[:,["Mon"]] 

Mon
week_1  9.5
week_2  9.0
week_3  8.5

Also, notice above that DataFrames dynamically create attributes for each column of data you have (assuming the columns are named with strings.) That's why you could do `scores.Mon` to get Monday's data as a Series. You'll see all the above techniques used in practice. Again, if you're not convinced yet, I strongly recommend that you go through the 10 minute tutorial carefully, and briefly summarize what you can in your own notes. Find some good cheat sheets for pandas online, or even make your own! AND – PAY CLOSE ATTENTION TO THE RETURN TYPES! It's very important to understand when `DataFrame` objects vs. `Series` objects are returned. It will save you lots of frustration down the road.

Let's continue

**15** [P] Show at least two different techniques to select scores for Tuesday using the string "Tue" as a `Series`

In [92]:
scores.loc[:,"Tue"]

week_1    8.75
week_2    8.00
week_3    8.00
Name: Tue, dtype: float64

In [93]:
scores["Tue"]

week_1    8.75
week_2    8.00
week_3    8.00
Name: Tue, dtype: float64

**16** [P] Show how to retrieve the scores for Tuesday using the named attribute `Tue`

In [94]:
scores.Tue

week_1    8.75
week_2    8.00
week_3    8.00
Name: Tue, dtype: float64

**17** [P] Show at least three techniques to select scores for Wednesday using an integer. The return type can be either a DataFrame or a Series.

In [102]:
scores.iloc[:,[2]]

Wed
week_1   8.00
week_2  10.00
week_3   9.75

In [103]:
scores.iloc[:,2]

week_1     8.00
week_2    10.00
week_3     9.75
Name: Wed, dtype: float64

In [104]:
scores.iloc[:,2:3]

Wed
week_1   8.00
week_2  10.00
week_3   9.75


**18** [P] Select the data for the first week using the string "week_1". Your result should return a Series representing the scores for week 1.


In [106]:
scores.loc["week_1"]

Mon     9.50
Tue     8.75
Wed     8.00
Thu    10.00
Fri     7.75
Name: week_1, dtype: float64


**19** [P] Select the data for the first week using the string "week_1". Your result should return a DataFrame, representing the subset of the scores DataFrame for week 1 only.


In [107]:
scores.loc[["week_1"]]

Mon   Tue  Wed   Thu   Fri
week_1  9.5  8.75  8.0  10.0  7.75


**20** [P] Select the data for the first week using a slice.

In [108]:
scores[0:1]

Mon   Tue  Wed   Thu   Fri
week_1  9.5  8.75  8.0  10.0  7.75


**21** [P] Use `.iloc` to select Monday and Friday of the first and third week. Your result should be a `DataFrame` that looks something as follows:

```python
        Mon   Fri
week_1	9.5	7.75
week_3	8.5	8.25
```

In [113]:
scores.iloc[[0,2],[0,4]]

Mon   Fri
week_1  9.5  7.75
week_3  8.5  8.25

**22** [P] Repeat the previous exercise, but use the `.loc` selector. You should have the same result.


In [114]:
scores.loc[["week_1", "week_3"], ["Mon", "Fri"]]

Mon   Fri
week_1  9.5  7.75
week_3  8.5  8.25

**23** [P] Report the mean score for each day. 

Your answer should look like:

```python
Mon    9.00
Tue    8.25
Wed    9.25
Thu    9.25
Fri    7.75
dtype: float64
```

In [116]:
scores.mean(axis=0)

Mon    9.00
Tue    8.25
Wed    9.25
Thu    9.25
Fri    7.75
dtype: float64

**24** [P] Report the mean score for each week.

Your answer should look like: 

```python
week_1    8.8
week_2    8.6
week_3    8.7
dtype: float64
```

In [117]:
scores.mean(axis=1)

week_1    8.8
week_2    8.6
week_3    8.7
dtype: float64

**25** [P] For each week, report how much each day's score for that week differed from the mean for the week. Your result should be one `DataFrame` that looks like this:

```python
	Mon	Tue	Wed	Thu	Fri
week_1	0.7	-0.05	-0.80	1.20	-1.05
week_2	0.4	-0.60	1.40	0.15	-1.35
week_3	-0.2	-0.70	1.05	0.30	-0.45
```


In [118]:
scores.sub(scores.mean(axis=1), axis = 0)

Mon   Tue   Wed   Thu   Fri
week_1  0.7 -0.05 -0.80  1.20 -1.05
week_2  0.4 -0.60  1.40  0.15 -1.35
week_3 -0.2 -0.70  1.05  0.30 -0.45

**26** [P] Report the maximum score for each week. Your result should be a `Series`.

In [119]:
scores.max(axis=1)

week_1    10.00
week_2    10.00
week_3     9.75
dtype: float64

**27** [P] For each week, report which day had the largest score. (Again, you should be reporting your result as a `Series`. And hint, `idxmax()` is pretty cool.)


In [121]:
scores.idxmax(axis=1)

week_1    Thu
week_2    Wed
week_3    Wed
dtype: object


**28** [P] Report the week that had the highest total quiz score. Your answer should only be the name of the week from the index.


In [122]:
scores.max(axis=1).idxmax()

'week_1'


**29** [P] How many days over the entire dataset had a score >= 9.25?


In [123]:
(scores >= 9.25).sum().sum()

4


**30** [P] Report the number of days of each week that had a score >= 9.25. Your answer should be a `Series` that looks like the following:

```python
week_1    2
week_2    1
week_3    1
dtype: int64
```

In [124]:
(scores >= 9.25).sum(axis=1)

week_1    2
week_2    1
week_3    1
dtype: int64

**31** [P] Report the average score for each week with the lowest score for each week dropped. (REMEMBER – NEVER hard code magic numbers. Your solution should work for any number of weeks, and any number of days per week!)

In [129]:
scores.apply(lambda row: row.nlargest(len(row)-1).mean(), axis = 1)

week_1    9.0625
week_2    8.9375
week_3    8.8750
dtype: float64

**32** [P] Report the scores rescaled to fall between 0 and 100, instead of 0 to 10 as they are now.

In [130]:
scores * 10

Mon   Tue    Wed    Thu   Fri
week_1  95.0  87.5   80.0  100.0  77.5
week_2  90.0  80.0  100.0   87.5  72.5
week_3  85.0  80.0   97.5   90.0  82.5

**33** [P] How would you convert your scores `DataFrame` to a Numpy array? Demonstrate it by showing the type of your conversion using Python's `type` function.

In [131]:
print(scores.to_numpy())
type(scores.to_numpy())

[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]
 [ 8.5   8.    9.75  9.    8.25]]


numpy.ndarray